### ISSUE TITLE
Consumers failing to build with v1.12.0

### ISSUE THREAD

**Issue by orlitzky** [sagemath/cysignals#212]
We just added v1.12.0 in Gentoo and switched the build to meson but now the packages that depend on it are failing to build: fpylll, primecountpy, cypari, pplpy, etc.

A typical error:

> 2024-11-22 07:13:20,452 root INFO building 'fpylll.fplll.wrapper' extension
> 2024-11-22 07:13:20,454 root INFO x86_64-pc-linux-gnu-g++ -O2 -pipe -march=native -fno-diagnostics-color -DNDEBUG -fPIC -Isrc/fpylll/fplll -I/usr/lib/python3.12/site-packages/cysignals -I/usr/include -I/usr/lib/python3.12/site-packages/numpy/_core/include -I/usr/include/python3.12 -c build/src/fpyll
> In file included from build/src/fpylll/fplll/lll.cpp:1353:
> /usr/lib/python3.12/site-packages/cysignals/macros.h: In function int _sig_on_prejmp(const char*, const char*, int):
> /usr/lib/python3.12/site-packages/cysignals/macros.h:117:5: error: cysigs was not declared in this scope
>   117 |     cysigs.s = message;
>       |     ^~~~~~

I tried to debug for a few minutes tonight but it will probably have to wait until next week.

**Comment by ludopulles** [comment]
Actually, already compiling the [basic example](https://cysignals.readthedocs.io/en/latest/interrupt.html#basic-example) with `cythonize -i FILE.pyx` gives me those errors (cython version 3.0.11).

It seems that the meson build system doesn't put `#include "macros.h"` after the late_includes `/* #### Code section: late_includes ### */`.

**Comment by antonio-rojas** [comment]
Caused by the removal of the line `# cython: preliminary_late_includes_cy28=True` from `signals.pxd` in https://github.com/sagemath/cysignals/commit/fa6d45d2ac1f88d45583a8431ddee811fb2bd617

**Comment by antonio-rojas** [comment]
> @antonio-rojas: Do these `# cython` directives in headers carry over to downstream projects?

Yes, adding that line back fixes the build issues in dependant projects

> If that's indeed the core issue, then a workaround for other projects would be to compile using `-X preliminary_late_includes_cy28=True`.

But why should other projects work around this when it's the cysignals header itself that needs it?

**Comment by ludopulles** [comment]
I agree with Antonio it's an issue within the `cysignals` package, not the dependent projects.
Compiling anything that depends on `cysignals` fails. CI should test this, no?

**Comment by videlec** [comment]
See also
- https://github.com/pyodide/pyodide/issues/5221
- https://github.com/flatsurf/surface-dynamics/issues/107

**Comment by user202729** [comment]
I just come across this recently. (which spawns an unrelated issue https://github.com/cython/cython/issues/6565 .)

Anyway, it's also worth pointing out that putting the header comment in a file that `cimport cysignals` doesn't work, you must put the header comment file in the `pxd` file provided by cython itself. So modifying the pxd looks like the best fix, otherwise you have to set the late import flag globally which may be undesirable.
